# Generated by Django 2.2 on 2020-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200716_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttable',
            name='DOB',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
