# Generated by Django 2.2 on 2020-07-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200716_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttable',
            name='DOB',
        ),
    ]
