# Generated by Django 2.2 on 2020-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patienttable_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttable',
            name='DOB',
            field=models.CharField(default='2000-23-11', max_length=250),
        ),
    ]
